const SQUARE_ORDER_URL='https://square.link/u/6tGjr89x?src=sms';
const INQUIRY_EMAIL='trappanyakillc@gmail.com';
const items={plates:[['Chicken Plate','$24.99','Fresh grilled chicken, garlic fried rice & hibachi vegetables.'],['Shrimp Plate','$29.99','Seasoned shrimp, garlic fried rice & hibachi vegetables.'],['Salmon Plate','$34.99','Grilled salmon with full-flavor sides.'],['Scallops Plate','$34.99','Seared scallops, fried rice & hibachi vegetables.'],['Ribeye Steak Plate','$39.99','Char-grilled ribeye, sliced to order.'],['Lobster Tail Plate','$44.99','Lobster tail with garlic fried rice & vegetables.']],combos:[['Chicken & Shrimp Plate','$29.99','Two favorites, one designer plate.'],['Steak & Shrimp Plate','$35.00','Savory steak with grilled shrimp.'],['Steak & Chicken Plate','$35.00','A bold double-protein combo.'],['Ribeye & Shrimp Plate','$49.99','Premium ribeye with grilled shrimp.'],['Ribeye & Lobster Plate','$54.99','The Trappanyaki upgrade.'],['Filet & Lobster Plate','$64.99','Our biggest premium combo.']],addons:[['Noodles','$9.99','Garlic noodles, made for the upgrade.'],['Extra Rice','$4.99','More garlic fried rice.'],['Extra Sauce','$1.99','Add another cup of signature sauce.'],['Add-on Shrimp','$7.99','Add grilled shrimp to any plate.'],['Lobster Tail Add-on','$19.99','Add a lobster tail to your order.'],['Filet Mignon Upgrade','$19.99','Upgrade your protein to filet.']]};
let active='plates',cart=[];const grid=document.querySelector('#menu-grid'),cartPanel=document.querySelector('#cart'),scrim=document.querySelector('#scrim');
function renderMenu(){grid.innerHTML=items[active].map((item,i)=>`<article class="menu-card reveal"><div><span class="eyebrow" style="color:var(--red);margin-bottom:12px">${active==='plates'?'PLATE':active==='combos'?'COMBO':'ADD-ON'} / ${String(i+1).padStart(2,'0')}</span><h3>${item[0]}</h3><p>${item[2]}</p></div><div><div class="menu-price">${item[1]}</div><button class="add-item" data-add="${item[0]}" data-price="${item[1]}">Add to order +</button></div></article>`).join('')}
function renderCart(){document.querySelector('#cart-count').textContent=cart.reduce((n,x)=>n+x.qty,0);const total=cart.reduce((n,x)=>n+x.price*x.qty,0);document.querySelector('#cart-total').textContent=`$${total.toFixed(2)}`;document.querySelector('#cart-items').innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-row"><div><strong>${x.name}</strong><span>Qty ${x.qty}</span></div><div><strong>$${(x.price*x.qty).toFixed(2)}</strong><button data-remove="${i}">Remove</button></div></div>`).join(''):'<p class="empty-cart">Your order is empty. Pick a plate to start.</p>'}
function openCart(){cartPanel.classList.add('open');scrim.classList.add('open');cartPanel.setAttribute('aria-hidden','false')}function closeCart(){cartPanel.classList.remove('open');scrim.classList.remove('open');cartPanel.setAttribute('aria-hidden','true')}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){const name=add.dataset.add,price=Number(add.dataset.price.replace('$','')),found=cart.find(x=>x.name===name);found?found.qty++:cart.push({name,price,qty:1});renderCart();toast(`${name} added to your order`)}const remove=e.target.closest('[data-remove]');if(remove){cart.splice(Number(remove.dataset.remove),1);renderCart()}const scroll=e.target.closest('[data-scroll]');if(scroll){document.querySelector(scroll.dataset.scroll).scrollIntoView({behavior:'smooth'})}if(e.target.closest('[data-open="cart"]'))openCart();if(e.target.closest('[data-close="cart"]')||e.target===scrim)closeCart();if(e.target.closest('[data-open="checkout"]')){if(!cart.length){toast('Pick a plate before checkout');return}window.open(SQUARE_ORDER_URL,'_blank','noopener,noreferrer');toast('Opening Square pickup ordering')}if(e.target.closest('[data-open="catering"]'))document.querySelector('#catering-dialog').showModal();if(e.target.closest('[data-close="catering"]'))document.querySelector('#catering-dialog').close()});
document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelector('.tab.active').classList.remove('active');tab.classList.add('active');active=tab.dataset.filter;renderMenu()}));
document.querySelector('#catering-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target),subject=encodeURIComponent(`Trappanyaki catering inquiry — ${data.get('name')}`),body=encodeURIComponent(`Name/company: ${data.get('name')}\nEvent date: ${data.get('date')}\nGuests: ${data.get('guests')}\nContact: ${data.get('contact')}\nDetails: ${data.get('details')||'None provided'}`);window.location.href=`mailto:${INQUIRY_EMAIL}?subject=${subject}&body=${body}`;e.target.hidden=true;document.querySelector('#form-success').hidden=false;toast('Opening your email app')});renderMenu();renderCart();
